### ISSUE TITLE
Gnome-Shell: Something has gone wrong

### ISSUE THREAD

**Issue by slackernetuk** [Dlackware/gnome-systemd#23]
Finally I've found time to build Gnome on a Slackware VMware Guest. I had some issues with vala and guile but I sort it out. :-) 

I prefer to start Gnome with startx, but I've got a error message:

`Something has gone wrong. A problem has occurred and the system can't recover. Please log out and try again.

How I can troubleshoot the gnome-shell?

My guess, I've to configure pam, I've just installed pam.

**Comment by belka-ew** [comment]
You can look into gnome-shell logs with `journalctl /usr/bin/gnome-shell` or `journalctl -xe`. Also check gdm logs in `/var/log/gdm` and Xorg logs /var/log/Xorg.0.log; it could be also some gdm/wayland issue.

**Comment by slackernetuk** [comment]
Thank you for your prompt reply. I've disabled gdm and start gnome with X11
```
export XDG_SESSION_TYPE=x11
export GDK_BACKEND=x11
exec gnome-session
```
journalctl -xe looks not very good

```
Mar 15 09:51:10 darkstar gnome-software[1548]: Failed to find one package for gnome-info-overview-panel.desktop, /usr/share/applications/gnome-info-overview-panel.desktop, [0]
Mar 15 09:51:10 darkstar kernel: gnome-shell[1510]: segfault at 30 ip 00007f8597f865c4 sp 00007ffc49983270 error 4 in libmutter-clutter-5.so.0.0.0[7f8597f2c000+89000]
Mar 15 09:51:10 darkstar kernel: Code: 7c 24 08 e8 8e ff ff ff 48 8b 7c 24 08 eb cf 0f 1f 80 00 00 00 00 41 57 41 56 41 55 49 89 fd 41 54 55 48 89 f5 53 48 83 ec 28 <4c> 8b 77 30 49 8b 86 08>
Mar 15 09:51:10 darkstar gnome-session-binary[1259]: Unrecoverable failure in required component org.gnome.Shell.desktop
Mar 15 09:51:10 darkstar gnome-session-binary[1259]: WARNING: Application 'org.gnome.Shell.desktop' killed by signal 11
```

**Comment by belka-ew** [comment]
what gnome/slackware version is this?

**Comment by slackernetuk** [comment]
Gnome 3.34.0 / Slackware current ( UpToDate )

**Comment by belka-ew** [comment]
Can you try to set `XDG_SESSION_TYPE` and/or `GDK_BACKEND` to wayland?

People are also suggesting to run something like `dbus-run-session -- gnome-shell --display-server --wayland` or `gnome-session --session gnome-wayland` (https://stackoverflow.com/questions/31213773/how-to-start-gnome-wayland-session-from-command-line) instead of startx. I'm not sure why gnome-shell crashes. I've built 3.34 some time ago and it worked but I tested it only with gdm.

Just for information since slackware current has experimental PAM support now, we're updating dlackware to work with stock slackware's PAM and I'm starting to update gnome to 3.36.0. So there are will be some big changes in the next weeks.

**Comment by slackernetuk** [comment]
I've sorted out.

1. I had to install your old PAM packages, the inactive Slackware packages doesn't work with 
    Gnome 3.34.
    `https://github.com/Dlackware/pam`

2. I also needed to downgrade vala 0.48.1 to 0.46.6, actually I had the same issues with Xfce.
    `https://bugzilla.xfce.org/show_bug.cgi?id=16426#c9`

3. Finally I've installed aisleriot manually, because there was a conflict with guile3.

thanks
